# Generated by Django 4.0.6 on 2022-09-30 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likers',
            field=models.ManyToManyField(default=None, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='unlikers',
            field=models.ManyToManyField(default=None, related_name='unliker', to=settings.AUTH_USER_MODEL),
        ),
    ]
